#pragma once

class Item;
class ItemPickaxe;
class ItemArmor;

namespace Items
{
	extern Item *flintAndSteel;
	extern Item *apple;
	extern Item *bow;
	extern Item *arrow;
	extern Item *ingotIron;
	extern Item *ingotGold;
	extern Item *swordWood;
	extern Item *shovelWood;
	extern ItemPickaxe *pickaxeWood;
	extern Item *axeWood;
	extern Item *stick;
	extern Item *hoeWood;
	extern Item *swordStone;
	extern Item *shovelStone;
	extern ItemPickaxe *pickaxeStone;
	extern Item *axeStone;
	extern Item *hoeStone;
	extern Item *seeds;
	extern Item *wheat;
	extern Item *bread;
	extern Item *cookie;
	extern Item *porkchopRaw;
	extern Item *porkchopCooked;
	extern Item *painting;
	extern Item *appleGold;
	extern Item *reed;
	extern Item *doorWood;
	extern Item *doorIron;
	extern Item *minecart;
	extern Item *minecartPowered;
	extern Item *minecartChest;
	extern Item *boat;
	extern Item *compass;
	extern Item *fishingRod;
	extern Item *clock;
	extern Item *record13;
	extern Item *recordCat;
	extern Item *coal;
	extern Item *diamond;
	extern Item *redstone;
	extern Item *dyePowder;
	extern Item *flint;
	extern Item *swordIron;
	extern Item *shovelIron;
	extern ItemPickaxe *pickaxeIron;
	extern Item *axeIron;
	extern Item *hoeIron;

	extern Item *swordDiamond;
	extern Item *shovelDiamond;
	extern ItemPickaxe *pickaxeDiamond;
	extern Item *axeDiamond;
	extern Item *hoeDiamond;

	extern Item *swordGold;
	extern Item *shovelGold;
	extern ItemPickaxe *pickaxeGold;
	extern Item *axeGold;
	extern Item *hoeGold;

	extern Item *leather;
	extern Item *silk;
	extern Item *feather;
	extern Item *gunpowder;
	extern Item *bowlEmpty;
	extern Item *bowlSoup;
	extern Item *bucketEmpty;
	extern Item *bucketWater;
	extern Item *bucketLava;
	extern Item *bucketMilk;
	extern Item *brick;
	extern Item *clayItem;
	extern Item *paper;
	extern Item *book;
	extern Item *sugar;
	extern Item *glowstoneDust;
	extern Item *fishRaw;
	extern Item *fishCooked;
	extern Item *bone;
	extern Item *sign;
	extern Item *redstoneRepeater;
	extern Item *snowball;
	extern Item *slimeball;
	extern Item *shears;
	extern Item *bed;
	extern Item *map;
	extern Item *cake;
	extern Item *egg;
	extern Item *saddle;
	extern ItemArmor *helmetLeather;
	extern ItemArmor *plateLeather;
	extern ItemArmor *legsLeather;
	extern ItemArmor *bootsLeather;
	extern ItemArmor *helmetChain;
	extern ItemArmor *plateChain;
	extern ItemArmor *legsChain;
	extern ItemArmor *bootsChain;
	extern ItemArmor *helmetIron;
	extern ItemArmor *plateIron;
	extern ItemArmor *legsIron;
	extern ItemArmor *bootsIron;
	extern ItemArmor *helmetDiamond;
	extern ItemArmor *plateDiamond;
	extern ItemArmor *legsDiamond;
	extern ItemArmor *bootsDiamond;
	extern ItemArmor *helmetGold;
	extern ItemArmor *plateGold;
	extern ItemArmor *legsGold;
	extern ItemArmor *bootsGold;
	void initItems();
}
